### ISSUE TITLE
NameError: name 'weather' is not defined

### ISSUE THREAD

**Issue by godnaked** [LennyHirsch/UnicornHatHD-Weather-Clock#2]
Hi Lenny, thank you for providing this nice code. I'm experiencing some issues when executing the py.

I'm new to programming but I think I understood, that >>> w = obs.get_weather() <<< retrieves an object called "weather" therefore the later-on code >>> if weather.lower() == 'rain': <<< should relate to it - I suppose. Anyhow I get the error: 

python weatherclock_o.py 
Traceback (most recent call last):
  File "weatherclock_o.py", line 126, in <module>
    if weather.lower() == 'rain':
NameError: name 'weather' is not defined

Do you have an idea how to fix it?

Best regards -J

**Comment by Griefed** [comment]
I'm having the exact same issue. 
`Traceback (most recent call last):
  File "./weatherclock.py", line 126, in <module>
    if weather.lower() == 'rain':
NameError: name 'weather' is not defined`

**Comment by LennyHirsch** [comment]
Hi, sorry it's taken me so long to get to this. I haven't worked on this code in a while, and have been very busy the last few years.

As godnaked commented, this is indeed the case. Weather should return what type of weather you're currently having: clouds, rain, sun, etc. The `.lower()` function ensures that this is all in lowercase i.e. not "Rain" or "RaIn", but "rain". From there, the if/elif/else statement sets colours depending on the weather conditions.

The script pulls weather info from pyOWM which is a python library for OpenWeatherMap's API. It may be the case that you don't have the API set up? You will need to enter your own API key on line 11, and enter your location on line 12 so the API can pull the correct data.

Try this and see if it works. If not, it may be that I have incorrectly named the variable on line 13. Perhaps renaming this to "weather" instead of "w" could work.

If this doesn't work, perhaps try and change the if/elif/else statement so it checks `w.detailed_status` instead of `weather.lower()`.

So line 126 would be `if w.detailed_status == 'rain':`
line 131: `elif w.detailed_status == 'clouds':`
line 136: `elif w.detailed_status == 'sunny':`

If that doesn't work, maybe try `w.detailed_status.lower()` to ensure everything is lower case as before.

Here is the documentation for pyOWM: https://pypi.org/project/pyowm/
Let me know if any of the above works to fix this issue. If not, I will try and have a closer look at this.

Again, sorry about the very long wait for this response!
